version: '3'
services:
  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "todos"
    ports:
      - 27017:27017
  backend:
    build: ./backend
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"