version: '3'
services:
  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "todos"
    ports:
      - 27017:27017
  backend:
    build: 
      context: ./backend/
    command: npm start
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"